### ISSUE TITLE
Create Database Table for order.js.

### ISSUE THREAD

**Issue by iiLegendNeverSleepsx** [Bro-Time/Bro-Time-Database#10]
It should be a maximum of 3 food items per order. Only 1 order at a time. After 1 order they can order again, they cannot order during a current order.

**Comment by cloewen8** [comment]
What do you consider a food item? Do you have multiple attributes that define food?

**Comment by iiLegendNeverSleepsx** [comment]
Hm, food items can mainly be a vote. We can do a vote on what we want the food to be based on for example cuisine etc.

**Comment by cloewen8** [comment]
Details need to be decided on before the table can be created.
